-- ----------------------------
-- 添加注释到 company operating 表
-- ----------------------------
ALTER TABLE `company operating`
  MODIFY COLUMN `SECURITY_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '证券 ID',
  MODIFY COLUMN `TICKER_SYMBOL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '股票代码',
  MODIFY COLUMN `INDIC_NAME_EN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '指标英文名称',
  MODIFY COLUMN `END_DATE` date NULL DEFAULT NULL COMMENT '截止日期',
  MODIFY COLUMN `VALUE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '指标值',
  MODIFY COLUMN `UNIT_CD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '单位代码';

-- ----------------------------
-- 添加注释到 macro industry 表
-- ----------------------------
ALTER TABLE `macro industry`
  MODIFY COLUMN `indic_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '指标 ID',
  MODIFY COLUMN `name_cn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '指标中文名称',
  MODIFY COLUMN `FREQUENCY_CD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '频率代码',
  MODIFY COLUMN `PERIOD_DATE` date NULL DEFAULT NULL COMMENT '周期日期',
  MODIFY COLUMN `DATA_VALUE` decimal(25, 5) NULL DEFAULT NULL COMMENT '数据值';

-- ----------------------------
-- 添加注释到 market data 表
-- ----------------------------
ALTER TABLE `market data`
  MODIFY COLUMN `SECURITY_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '证券 ID',
  MODIFY COLUMN `TICKER_SYMBOL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '股票代码',
  MODIFY COLUMN `END_DATE` date NULL DEFAULT NULL COMMENT '截止日期',
  MODIFY COLUMN `CLOSE_PRICE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '收盘价格',
  MODIFY COLUMN `TURNOVER_VOL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '成交量',
  MODIFY COLUMN `TURNOVER_VALUE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '成交金额',
  MODIFY COLUMN `MARKET_VALUE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '市值',
  MODIFY COLUMN `TYPE_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '类型 ID',
  MODIFY COLUMN `TYPE_NAME_EN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '类型英文名称',
  MODIFY COLUMN `TYPE_NAME_CN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '类型中文名称';


-- ----------------------------
-- 为 income statement 表的所有字段添加注释
-- ----------------------------
ALTER TABLE `income statement`
  MODIFY COLUMN `PARTY_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '参与方 ID',
  MODIFY COLUMN `TICKER_SYMBOL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '股票代码',
  MODIFY COLUMN `EXCHANGE_CD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '交易所代码',
  MODIFY COLUMN `PUBLISH_DATE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '发布日期',
  MODIFY COLUMN `END_DATE_REP` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '报告截止日期',
  MODIFY COLUMN `END_DATE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '截止日期',
  MODIFY COLUMN `REPORT_TYPE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '报告类型',
  MODIFY COLUMN `FISCAL_PERIOD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '财务期',
  MODIFY COLUMN `MERGED_FLAG` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '合并标志',
  MODIFY COLUMN `T_REVENUE` decimal(25, 0) NULL DEFAULT NULL COMMENT '总收入',
  MODIFY COLUMN `REVENUE` decimal(25, 0) NULL DEFAULT NULL COMMENT '主营业务收入',
  MODIFY COLUMN `INT_INCOME` decimal(25, 0) NULL DEFAULT NULL COMMENT '利息收入',
  MODIFY COLUMN `PREM_EARNED` decimal(25, 0) NULL DEFAULT NULL COMMENT '已赚保费',
  MODIFY COLUMN `COMMIS_INCOME` decimal(25, 0) NULL DEFAULT NULL COMMENT '手续费收入',
  MODIFY COLUMN `SPEC_TOR` decimal(25, 0) NULL DEFAULT NULL COMMENT '专项营业收入',
  MODIFY COLUMN `ATOR` decimal(25, 0) NULL DEFAULT NULL COMMENT '总营业收入',
  MODIFY COLUMN `T_COGS` decimal(25, 0) NULL DEFAULT NULL COMMENT '总销售成本',
  MODIFY COLUMN `COGS` decimal(25, 0) NULL DEFAULT NULL COMMENT '主营业务成本',
  MODIFY COLUMN `INT_EXP` decimal(25, 0) NULL DEFAULT NULL COMMENT '利息支出',
  MODIFY COLUMN `COMMIS_EXP` decimal(25, 0) NULL DEFAULT NULL COMMENT '手续费支出',
  MODIFY COLUMN `PREM_REFUND` decimal(25, 0) NULL DEFAULT NULL COMMENT '退保费',
  MODIFY COLUMN `N_COMPENS_PAYOUT` decimal(25, 0) NULL DEFAULT NULL COMMENT '赔付支出净额',
  MODIFY COLUMN `RESER_INSUR_CONTR` decimal(25, 0) NULL DEFAULT NULL COMMENT '提取保险合同准备金净额',
  MODIFY COLUMN `POLICY_DIV_PAYT` decimal(25, 0) NULL DEFAULT NULL COMMENT '保单红利支出',
  MODIFY COLUMN `REINSUR_EXP` decimal(25, 0) NULL DEFAULT NULL COMMENT '分保费用',
  MODIFY COLUMN `BIZ_TAX_SURCHG` decimal(25, 0) NULL DEFAULT NULL COMMENT '营业税金及附加',
  MODIFY COLUMN `SELL_EXP` decimal(25, 0) NULL DEFAULT NULL COMMENT '销售费用',
  MODIFY COLUMN `ADMIN_EXP` decimal(25, 0) NULL DEFAULT NULL COMMENT '管理费用',
  MODIFY COLUMN `FINAN_EXP` decimal(25, 0) NULL DEFAULT NULL COMMENT '财务费用',
  MODIFY COLUMN `ASSETS_IMPAIR_LOSS` decimal(25, 0) NULL DEFAULT NULL COMMENT '资产减值损失',
  MODIFY COLUMN `SPEC_TOC` decimal(25, 0) NULL DEFAULT NULL COMMENT '专项营业成本',
  MODIFY COLUMN `ATOC` decimal(25, 0) NULL DEFAULT NULL COMMENT '总营业成本',
  MODIFY COLUMN `F_VALUE_CHG_GAIN` decimal(25, 0) NULL DEFAULT NULL COMMENT '公允价值变动收益',
  MODIFY COLUMN `INVEST_INCOME` decimal(25, 0) NULL DEFAULT NULL COMMENT '投资收益',
  MODIFY COLUMN `A_J_INVEST_INCOME` decimal(25, 0) NULL DEFAULT NULL COMMENT '对联营企业和合营企业的投资收益',
  MODIFY COLUMN `FOREX_GAIN` decimal(25, 0) NULL DEFAULT NULL COMMENT '汇兑收益',
  MODIFY COLUMN `OTH_EFFECT_OP` decimal(25, 0) NULL DEFAULT NULL COMMENT '其他营业外影响（营业）',
  MODIFY COLUMN `ASSETS_DISP_GAIN` decimal(25, 0) NULL DEFAULT NULL COMMENT '资产处置收益',
  MODIFY COLUMN `AE_EFFECT_OP` decimal(25, 0) NULL DEFAULT NULL COMMENT '累计调整对营业的影响',
  MODIFY COLUMN `OTH_GAIN` decimal(25, 0) NULL DEFAULT NULL COMMENT '其他收益',
  MODIFY COLUMN `OPERATE_PROFIT` decimal(25, 0) NULL DEFAULT NULL COMMENT '营业利润',
  MODIFY COLUMN `NOPERATE_INCOME` decimal(25, 0) NULL DEFAULT NULL COMMENT '营业外收入',
  MODIFY COLUMN `NOPERATE_EXP` decimal(25, 0) NULL DEFAULT NULL COMMENT '营业外支出',
  MODIFY COLUMN `NCA_DISPLOSS` decimal(25, 0) NULL DEFAULT NULL COMMENT '非流动资产处置损失',
  MODIFY COLUMN `OTH_EFFECT_TP` decimal(25, 0) NULL DEFAULT NULL COMMENT '其他营业外影响（总）',
  MODIFY COLUMN `AE_EFFECT_TP` decimal(25, 0) NULL DEFAULT NULL COMMENT '累计调整对总利润的影响',
  MODIFY COLUMN `T_PROFIT` decimal(25, 0) NULL DEFAULT NULL COMMENT '利润总额',
  MODIFY COLUMN `INCOME_TAX` decimal(25, 0) NULL DEFAULT NULL COMMENT '所得税费用',
  MODIFY COLUMN `OTH_EFFECT_NP` decimal(25, 0) NULL DEFAULT NULL COMMENT '其他营业外影响（净利润）',
  MODIFY COLUMN `AE_EFFECT_NP` decimal(25, 0) NULL DEFAULT NULL COMMENT '累计调整对净利润的影响',
  MODIFY COLUMN `N_INCOME` decimal(25, 0) NULL DEFAULT NULL COMMENT '净利润',
  MODIFY COLUMN `GOING_CONCERN_NI` decimal(25, 0) NULL DEFAULT NULL COMMENT '持续经营净利润',
  MODIFY COLUMN `QUIT_CONCERN_NI` decimal(25, 0) NULL DEFAULT NULL COMMENT '终止经营净利润',
  MODIFY COLUMN `N_INCOME_ATTR_P` decimal(25, 0) NULL DEFAULT NULL COMMENT '归属于母公司股东的净利润',
  MODIFY COLUMN `N_INCOME_BMA` decimal(25, 0) NULL DEFAULT NULL COMMENT '归属于少数股东的净利润',
  MODIFY COLUMN `MINORITY_GAIN` decimal(25, 0) NULL DEFAULT NULL COMMENT '少数股东损益',
  MODIFY COLUMN `OTH_EFFECT_NPP` decimal(25, 0) NULL DEFAULT NULL COMMENT '其他营业外影响（少数股东损益）',
  MODIFY COLUMN `AE_EFFECT_NPP` decimal(25, 0) NULL DEFAULT NULL COMMENT '累计调整对少数股东损益的影响',
  MODIFY COLUMN `BASIC_EPS` decimal(25, 0) NULL DEFAULT NULL COMMENT '基本每股收益',
  MODIFY COLUMN `DILUTED_EPS` decimal(25, 0) NULL DEFAULT NULL COMMENT '稀释每股收益',
  MODIFY COLUMN `OTH_COMPR_INCOME` decimal(25, 0) NULL DEFAULT NULL COMMENT '其他综合收益',
  MODIFY COLUMN `OTH_EFFECT_CI` decimal(25, 0) NULL DEFAULT NULL COMMENT '其他综合收益的其他营业外影响',
  MODIFY COLUMN `AE_EFFECT_CI` decimal(25, 0) NULL DEFAULT NULL COMMENT '累计调整对综合收益的影响',
  MODIFY COLUMN `T_COMPR_INCOME` decimal(25, 0) NULL DEFAULT NULL COMMENT '综合收益总额',
  MODIFY COLUMN `COMPR_INC_ATTR_P` decimal(25, 0) NULL DEFAULT NULL COMMENT '归属于母公司股东的综合收益总额',
  MODIFY COLUMN `COMPR_INC_ATTR_M_S` decimal(25, 0) NULL DEFAULT NULL COMMENT '归属于少数股东的综合收益总额',
  MODIFY COLUMN `OTH_EFFECT_PCI` decimal(25, 0) NULL DEFAULT NULL COMMENT '其他综合收益影响（母公司股东部分）',
  MODIFY COLUMN `AE_EFFECT_PCI` decimal(25, 0) NULL DEFAULT NULL COMMENT '累计调整对综合收益的影响（母公司股东部分）';